{% set name = "sdmetrics" %}
{% set version = "0.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sdmetrics-{{ version }}.tar.gz
  sha256: 866c999b5c79613ec76775920e6ab1f1d60ce40441e09ee6e0f5c5b81b181a42

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python {{ python_min }}
    - setuptools
  run:
    - copulas >=0.12.1
    - numpy >=1.21.0
    - pandas >=1.4.0
    - plotly >=5.19.0,<6
    - python >={{ python_min }},<3.14
    - scikit-learn >=1.0.2,<2
    - scipy >=1.7.3,<2
    - tqdm >=4.29

test:
  imports:
    - sdmetrics
    - sdmetrics.column_pairs
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/sdv-dev/SDMetrics
  summary: Metrics for Synthetic Data Generation Projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
