{% set name = "sdmetrics" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdmetrics-{{ version }}.tar.gz
  sha256: 507ae34826b0f1c97536b7931013b8704145da896d11973810e49379508764ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.13
  run:
    - copulas >=0.11.0
    - numpy >=1.21.0
    - pandas >=1.4.0
    - plotly >=5.19.0,<6
    - python >=3.8,<3.13
    - scikit-learn >=1.0.2,<2
    - scipy >=1.7.3,<2
    - tqdm >=4.29

test:
  imports:
    - sdmetrics
    - sdmetrics.column_pairs
  requires:
    - pip
    - pytest

about:
  home: https://github.com/sdv-dev/SDMetrics
  summary: Metrics for Synthetic Data Generation Projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
