{% set name = "sdmetrics" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdmetrics-{{ version }}.tar.gz
  sha256: 278a79f7521e742c06c55a7890589e851b2958c60ecd86b2380a6730fb61df19

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.10
  run:
    - copulas >=0.7.0,<0.8
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - python >=3.6,<3.10
    - scikit-learn >=0.24,<2
    - scipy >=1.5.4,<2
    - pytorch >=1.4.0,<2

test:
  imports:
    - sdmetrics
    - sdmetrics.column_pairs
  commands:
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests/unit
    - tests/utils.py

about:
  home: https://github.com/sdv-dev/SDMetrics
  summary: Metrics for Synthetic Data Generation Projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
