{% set name = "sdmetrics" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdmetrics-{{ version }}.tar.gz
  sha256: fcbdaec40980a9550f4484fed29b8495a68c33b063109161fd166637534800e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.12
  run:
    - copulas >=0.10.0,<0.11
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - plotly >=5.10.0,<6
    - python >=3.8,<3.12
    - scikit-learn >=0.24,<2
    - scipy >=1.5.4,<2
    - tqdm >=4.15,<5

test:
  imports:
    - sdmetrics
    - sdmetrics.column_pairs
  requires:
    - pip
    - pytest

about:
  home: https://github.com/sdv-dev/SDMetrics
  summary: Metrics for Synthetic Data Generation Projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
