{% set name = "sdmetrics" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdmetrics-{{ version }}.tar.gz
  sha256: e6055253aacd2d3f2192e56ce66df4d1f64787f9417f2b7c699ba0252192561d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.13
  run:
    - copulas >=0.11.0
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - plotly >=5.19.0,<6
    - python >=3.8,<3.13
    - scikit-learn >=0.24,<2
    - scipy >=1.5.4,<2
    - tqdm >=4.29

test:
  imports:
    - sdmetrics
    - sdmetrics.column_pairs
  requires:
    - pip
    - pytest

about:
  home: https://github.com/sdv-dev/SDMetrics
  summary: Metrics for Synthetic Data Generation Projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
