{% set name = "sdmetrics" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sdmetrics-{{ version }}.tar.gz
  sha256: 28df1cdd6988b3464306c1d189da19ee13a49023c53ca8b3db399fc9fd45fae8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.10
  run:
    - copulas >=0.6.0,<0.7
    - numpy >=1.18.0,<2
    - pandas >=1.1.3,<2
    - python >=3.6,<3.10
    - pyts >=0.12.0,<0.13.0
    - rdt >=0.6.1,<0.7
    - scikit-learn >=0.24,<2
    - scipy >=1.5.4,<2
    - pytorch >=1.4.0,<2
    - numba

test:
  imports:
    - sdmetrics
    - sdmetrics.column_pairs
  commands:
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests/unit

about:
  home: https://github.com/sdv-dev/SDMetrics
  summary: Metrics for Synthetic Data Generation Projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
